/*
  ____  _       _            _             _       
 / ___|(_)_ __ | | __  _ __ | |_   _  __ _(_)_ __  
 \___ \| | '_ \| |/ / | '_ \| | | | |/ _` | | '_ \ 
  ___) | | | | |   <  | |_) | | |_| | (_| | | | | |
 |____/|_|_| |_|_|\_\ | .__/|_|\__,_|\__, |_|_| |_|
                      |_|            |___/         
# A Template for MachinetoolPlugin, a Sink Plugin
# Generated by the command: plugin -t sink machinetool -d mt_plugin
# Hostname: Fram-IV.local
# Current working directory: /Users/p4010/Develop/MADS_plugins
# Creation date: 2026-03-05T19:28:13.964+0100
# NOTICE: MADS Version 2.0.0
*/

// Mandatory included headers
#include <sink.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>
#include "machine_viewer.hpp"

// other includes as needed here
#include <array>
#include <chrono>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <thread>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "machinetool"
#endif

// Load the namespaces
using namespace std;
using json = nlohmann::json;


// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class MachinetoolPlugin : public Sink<json> {

public:

  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {
    (void)topic;
    (void)blob;

    if (!_viewer) {
      _error = "MachineViewer is not initialized. Check plugin parameters.";
      return return_type::error;
    }

    try {
      if (!input.contains("position")) {
        _error = "Input JSON is missing 'position' field.";
        return return_type::warning;
      }

      const auto position = parse_position(input.at("position"));
      _viewer->update_position(position);

      if (input.contains("tool")) {
        if (!input.at("tool").is_object()) {
          _error = "Input field 'tool' must be an object with 'length' and 'diameter'.";
          return return_type::warning;
        }

        const auto& tool = input.at("tool");
        if (!tool.contains("length") || !tool.contains("diameter")) {
          _error = "Input field 'tool' must contain both 'length' and 'diameter'.";
          return return_type::warning;
        }
        if (!tool.at("length").is_number() || !tool.at("diameter").is_number()) {
          _error = "Input fields 'tool.length' and 'tool.diameter' must be numeric.";
          return return_type::warning;
        }

        _viewer->load_tool(tool.at("length").get<double>(), tool.at("diameter").get<double>());
      }

      if (input.contains("metrics")) {
        if (!input.at("metrics").is_object()) {
          _error = "Input field 'metrics' must be an object of scalar values.";
          return return_type::warning;
        }

        for (const auto& [name, value] : input.at("metrics").items()) {
          if (!value.is_number()) {
            _error = "Metric '" + name + "' is not numeric.";
            return return_type::warning;
          }
          _viewer->log_scalar(name, value.get<double>());
        }
      }
    } catch (const exception& ex) {
      _error = string("Failed to process input: ") + ex.what();
      return return_type::error;
    }

    return return_type::success;
  }

  void set_params(const json &params) override { 
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Sink::set_params(params);

    _params["models_path"] = "models";
    _params["recording_name"] = "machinetool";
    _params["stacking"] = {
      {"x", "ground"},
      {"z", "x"},
      {"y", "z"},
    };
    _params["model_files"] = {
      {"ground", "ground.obj"},
      {"x", "x_axis.obj"},
      {"y", "y_axis.obj"},
      {"z", "z_axis.obj"},
    };
    _params["initial_position"] = {0.0, 0.0, 0.0};
    _params["tool"] = json::object();

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);

    // Finally, initialize members hereafter
    try {
      auto models_path = _params.at("models_path").get<string>();
      auto recording_name = _params.at("recording_name").get<string>();
      auto stacking = parse_map_field(_params.at("stacking"), "stacking");
      auto model_files = parse_map_field(_params.at("model_files"), "model_files");
      auto initial_position = parse_position(_params.at("initial_position"));
      if (_params.contains("tool_z_offset")) {
        throw invalid_argument(
          "Field 'tool_z_offset' is no longer supported. Use 'tool.z_offset' instead."
        );
      }
      const auto tool = parse_setup_tool(_params.at("tool"));

      _viewer = make_unique<MachineViewer>(
        models_path,
        stacking,
        model_files,
        recording_name,
        tool.z_offset
      );
      _viewer->update_position(initial_position);
      if (tool.has_geometry) {
        _viewer->load_tool(tool.length, tool.diameter);
      }

      _init_info["models_path"] = models_path;
      _init_info["recording_name"] = recording_name;
      _init_info["stacking"] = _params.at("stacking").dump();
      _init_info["model_files"] = _params.at("model_files").dump();
      _init_info["initial_position"] = _params.at("initial_position").dump();
      _init_info["tool"] = _params.at("tool").dump();
      _init_info["viewer_initialized"] = "true";

    } catch (const exception& ex) {
      _viewer.reset();
      _init_info["viewer_initialized"] = "false";
      _init_info["initialization_error"] = ex.what();
      _error = string("Failed to initialize MachineViewer: ") + ex.what();
      throw runtime_error(_error);
    }
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return _init_info;
    
  };

private:
  struct setup_tool_t {
    bool has_geometry = false;
    double length = 0.0;
    double diameter = 0.0;
    double z_offset = 0.0;
  };

  static setup_tool_t parse_setup_tool(const json& value) {
    if (!value.is_object()) {
      throw invalid_argument(
        "Field 'tool' must be an object and can only contain: length, diameter, z_offset."
      );
    }

    for (const auto& [key, element] : value.items()) {
      (void)element;
      if (key != "length" && key != "diameter" && key != "z_offset") {
        throw invalid_argument("Field 'tool' contains unsupported key '" + key + "'.");
      }
    }

    const bool has_length = value.contains("length");
    const bool has_diameter = value.contains("diameter");
    const bool has_z_offset = value.contains("z_offset");

    if (has_length != has_diameter) {
      throw invalid_argument(
        "Field 'tool' must contain both 'length' and 'diameter' together, or neither."
      );
    }

    setup_tool_t tool;
    if (has_length && has_diameter) {
      if (!value.at("length").is_number() || !value.at("diameter").is_number()) {
        throw invalid_argument("Fields 'tool.length' and 'tool.diameter' must be numeric.");
      }
      tool.has_geometry = true;
      tool.length = value.at("length").get<double>();
      tool.diameter = value.at("diameter").get<double>();
    }

    if (has_z_offset) {
      if (!value.at("z_offset").is_number()) {
        throw invalid_argument("Field 'tool.z_offset' must be numeric.");
      }
      tool.z_offset = value.at("z_offset").get<double>();
    }

    return tool;
  }

  static map<string, string> parse_map_field(const json& value, const string& field_name) {
    if (!value.is_object()) {
      throw invalid_argument("Field '" + field_name + "' must be an object.");
    }

    map<string, string> out;
    for (const auto& [key, element] : value.items()) {
      if (!element.is_string()) {
        throw invalid_argument("Field '" + field_name + "." + key + "' must be a string.");
      }
      out[key] = element.get<string>();
    }
    return out;
  }

  static array<double, 3> parse_position(const json& value) {
    if (!value.is_array() || value.size() != 3) {
      throw invalid_argument("Position must be an array of exactly 3 numbers.");
    }
    if (!value[0].is_number() || !value[1].is_number() || !value[2].is_number()) {
      throw invalid_argument("Position array must contain only numeric values.");
    }

    return {value[0].get<double>(), value[1].get<double>(), value[2].get<double>()};
  }

  unique_ptr<MachineViewer> _viewer;
  map<string, string> _init_info;
};



/*
  ____  _             _             _      _                
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __ 
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |   
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|   
                |___/                                      
Enable the class as plugin 
*/
INSTALL_SINK_DRIVER(MachinetoolPlugin, json)


/*
                  _
  _ __ ___   __ _(_)_ __
 | '_ ` _ \ / _` | | '_ \
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|

For testing purposes, when directly executing the plugin
*/
int main(int argc, char const *argv[]) {
  try {
    MachinetoolPlugin plugin;
    json params;

    params["models_path"] = argc > 1 ? argv[1] : "models";
    params["stacking"] = {
      {"x", "ground"},
      {"z", "x"},
      {"y", "z"},
    };
    params["model_files"] = {
      {"ground", "ground.obj"},
      {"x", "x_axis.obj"},
      {"y", "y_axis.obj"},
      {"z", "z_axis.obj"},
    };
    params["initial_position"] = {0.0, 0.0, 0.0};
    params["recording_name"] = "machinetool_plugin_test";

    plugin.set_params(params);

    constexpr int total_steps = 50;
    constexpr chrono::milliseconds tick{100};
    for (int i = 0; i <= total_steps; ++i) {
      const double alpha = static_cast<double>(i) / static_cast<double>(total_steps);
      const double position = 0.5 * alpha;
      json input;
      input["position"] = {position, position, position};
      input["metrics"] = {{"progress", alpha}};

      const auto result = plugin.load_data(input);
      if (result != return_type::success) {
        return 1;
      }

      if (i < total_steps) {
        this_thread::sleep_for(tick);
      }
    }
  } catch (const exception&) {
    return 1;
  }

  return 0;
}
